### ISSUE TITLE
Define is not defined

### ISSUE THREAD

**Issue by glenngijsberts** [lordazzi/calc-js#15]
When we tried this package for our Next.js application (With SSR) we got an error on render

```
Define is not defined
```

<img width="1053" alt="Schermafbeelding 2019-08-02 om 11 55 55" src="https://user-images.githubusercontent.com/14276144/62362544-7a2d9f00-b51d-11e9-94dd-d4cbae029f5b.png">

It's coming from the library, but we are not sure where from. It's probably an issue with something being used that's not available in node.js, since we're getting it on page reload but not when the app was already mounted. 

Are there any plans to support server side rendering?

**Comment by lordazzi** [comment]
Yes, we do have... 
Import via JavaScript is not working correctly as the library was primarily developed for TypeScript. This is an unfortunate failure on my part.
Once you have time, apply a solution to your problem, thanks for reporting.

If you are willing to assist me in correcting this problem in the library, I will be happy to accept Pull Request, run Travys, and generate a new build making the fix available.

**Comment by lordazzi** [comment]
Fixed on version 2.0.1. Please update.

**Comment by lordazzi** [comment]
Fixed on version 2.0.1. Please update.
